<?php

namespace App\Domains\Auth\Notifications;

use App\Domains\Auth\Models\User;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Sent when an admin/super_admin creates a user in "invite" mode (see
 * UserController::store()) — reuses Laravel's own password-reset broker
 * rather than a custom invitation token/URL, so the link inherits the
 * framework's own expiry/hashing/throttling.
 */
class WelcomeSetPasswordNotification extends Notification
{
    /**
     * Generated by the caller (Password::createToken(), see
     * UserController::store()) and passed in via the constructor —
     * not computed lazily inside toMail() — so it's readable on the
     * notification instance under Notification::fake() the same way
     * core Laravel's own ResetPassword notification exposes ->token
     * (its token is likewise built by the broker before the
     * notification is constructed, not inside toMail()).
     */
    public function __construct(public readonly string $token) {}

    /** @return array<int, string> */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(User $notifiable): MailMessage
    {
        $resetUrl = route('password.reset', [
            'token' => $this->token,
            'email' => $notifiable->getEmailForPasswordReset(),
        ]);

        return (new MailMessage)
            ->subject(__('Bienvenue — définissez votre mot de passe'))
            ->greeting(__('Bonjour :name,', ['name' => $notifiable->name]))
            ->line(__('Un compte vient d\'être créé pour vous.'))
            ->line(__('Veuillez définir votre mot de passe pour y accéder.'))
            ->action(__('Définir mon mot de passe'), $resetUrl)
            ->line(__('Ce lien expirera dans :count minutes.', [
                'count' => config('auth.passwords.'.config('auth.defaults.passwords').'.expire'),
            ]));
    }
}
